GruppAKonsult/Models/CV.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using GruppAKonsult.ViewModels;

    public partial class CV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CV()
        {
            this.Profession = new HashSet<Profession>();
        }


        public int CV_Id { get; set; }
        public int Candidate_Id { get; set; }
        public string Drivinglicense { get; set; }
        public string Description { get; set; }
        public string Education { get; set; }
        public string Workexperience { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profession> Profession { get; set; }
    }
}

GruppAKonsult/ViewModels/CVViewModel.cs
using GruppAKonsult.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GruppAKonsult.ViewModels
{
    public class CVViewModel
    {
        public CVViewModel()
        {
            AddLanguageList();
            AddProfessionList();
            AddSkillsList();
            AddCityList();
        }

        //Egenskaper från CV
        public string Drivinglicense { get; set; }
        public string Description { get; set; }
        public string Education { get; set; }
        public string Workexperience { get; set; }

        //Egenskaper från employer   
        public string Companyname { get; set; }
        public string Email { get; set; }
        //public Nullable<int> Phonenumber { get; set; }
        public int Phonenumber { get; set; }

        //Egenskaper från freelancer
        public int Candidate_Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        //public Nullable<int> Postalnumber { get; set; }
        public int Postalnumber { get; set; }

        public string City { get; set; }
        //public Nullable<int> Birthdate { get; set; }

        public int Birthdate { get; set; }
        public string Cityofbirth { get; set; }

        //Onödig??
        //public List<Language> Language { get; set; }
        //public List<Skills> Skills { get; set; }
        //public List<Profession> Profession { get; set; }

        public Freelancer Freelancer { get; set; }

        public CV CV { get; set; }

        //public string[] SelectedLanguages { get; set; }

        //public string[] SelectedProfessions { get; set; }

        //public string[] SelectedSkills { get; set; }

        public string SelectedProfession { get; set; }

        public string SelectedSkill { get; set; }

        public string SelectedLanguage { get; set; }

        public string SelectedCity { get; set; }

        public IEnumerable<SelectListItem> LanguageList { get; set; }

        public IEnumerable<SelectListItem> ProfessionList { get; set; }

        public IEnumerable<SelectListItem> SkillsList { get; set; }

        public IEnumerable<SelectListItem> CityList { get; set; }

        private void AddLanguageList()
        {
            LanguageList = new List<SelectListItem>()
            {
                
                new SelectListItem { Value = "2", Text = "Svenska"},
                new SelectListItem { Value = "3", Text = "Engelska"},
                new SelectListItem { Value = "4", Text = "Franska"},
                new SelectListItem { Value = "5", Text = "Spanska"},
                new SelectListItem { Value = "6", Text = "Tyska"},
                new SelectListItem { Value = "7", Text = "Norska"},
                new SelectListItem { Value = "8", Text = "Danska"},
                new SelectListItem { Value = "9", Text = "Finska"}

            };
        }

        private void AddProfessionList()
        {
            ProfessionList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Välj Yrkesområde" },
                new SelectListItem { Value = "2", Text = "Webbutvecklare" },
                new SelectListItem { Value = "3", Text = "Systemutvecklare" },
                new SelectListItem { Value = "4", Text = "Programmerare" },
                new SelectListItem { Value = "5", Text = "Mjukvaruutveklare" },
                new SelectListItem { Value = "6", Text = "Frontendutvecklare" },
                new SelectListItem { Value = "7", Text = "Backendutvecklare" },
                new SelectListItem { Value = "8", Text = "Javautvecklare" },
                new SelectListItem { Value = "9", Text = "Scrummaster" }
            };
        }

        private void AddSkillsList()
        {
            SkillsList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Välj Kompetens" },
                new SelectListItem { Value = "2", Text = "C#" },
                new SelectListItem { Value = "3", Text = "JavaScript" },
                //new SelectListItem { Value = "4", Text = "Java" },
                new SelectListItem { Value = "5", Text = "C++" },
                new SelectListItem { Value = "6", Text = "JQuery" },
                new SelectListItem { Value = "7", Text = "HTML" },
                new SelectListItem { Value = "8", Text = "CSS" },
                new SelectListItem { Value = "9", Text = "SQL" }
            };
        }

        private void AddCityList()
        {
            CityList = new List<SelectListItem>()
            {
                new SelectListItem { Value = "1", Text = "Helsingborg" },
                new SelectListItem { Value = "2", Text = "Kristianstad" },
                new SelectListItem { Value = "3", Text = "Landskrona" },
                new SelectListItem { Value = "4", Text = "Lund" },
                new SelectListItem { Value = "5", Text = "Malmö" },
                new SelectListItem { Value = "6", Text = "Ystad" },
                new SelectListItem { Value = "7", Text = "Stockholm" },
                new SelectListItem { Value = "7", Text = "Göteborg" }
            };
        }

    }
}




           

GruppAKonsult/Controllers/CVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GruppAKonsult.Models;
using GruppAKonsult.ViewModels;

namespace GruppAKonsult.Controllers
{
    public class CVsController : Controller
    {
        GruppAKonsult_dbEntities2 db = new GruppAKonsult_dbEntities2();
        // GET: CVs
        public ActionResult Index()
        {           
            CVViewModel cvvm = new CVViewModel();
            List<CV> ListOfCv = new List<CV>();
            var freelancercv = db.CV.Include(c => c.Freelancer);

            //var listOfProfessions = ();
            return View(freelancercv.ToList());
        }


       // GET: CVs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CV cV = db.CV.Find(id);
            if (cV == null)
            {
                return HttpNotFound();
            }
            return View(cV);
        }

        // GET: CVs/Create
        public ActionResult Create()
        {
            ViewBag.Candidate_Id = new SelectList(db.Freelancer, "Candidate_Id", "Firstname");
            return View();
        }

        // POST: CVs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CV_Id,Candidate_Id,Drivinglicense,Description,Education,Workexperience")] CV cV)
        {
            if (ModelState.IsValid)
            {
                db.CV.Add(cV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Candidate_Id = new SelectList(db.Freelancer, "Candidate_Id", "Firstname", cV.Candidate_Id);
            return View(cV);
        }
        //Kommenterat bort koden nedan sålänge då den inte fungerar i nuläget

        //public ActionResult Edit(int? Candidate_Id)
        //{
        //    if (Candidate_Id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var cvvm = new CVViewModel
        //    {
        //        Cv = db.CV.Include(i => i.Profession).First(i => i.Candidate_Id == Candidate_Id),
        //    };
        //    if (cvvm.Cv == null)
        //        return HttpNotFound();
        //    var professionList = db.Profession.ToList();
        //    cvvm.AllProfessions = professionList.Select(o => new SelectListItem
        //    {
        //        Text = o.Backenddeveloper,
        //        Value = o.Candidate_Id.ToString()
        //    });
        //    ViewBag.EmployerID =
        //    new SelectList(db.CV, "Candidate_Id", "Profession",
        //    cvvm.Cv.Candidate_Id);
        //    return View(cvvm);
        //}

        // GET: CVs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    CV cV = db.CV.Find(id);
        //    if (cV == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.Candidate_Id = new SelectList(db.Freelancer, "Candidate_Id", "Firstname", cV.Candidate_Id);
        //    return View(cV);
        //}

        // POST: CVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CV_Id,Candidate_Id,Drivinglicense,Description,Education,Workexperience")] CV cV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Candidate_Id = new SelectList(db.Freelancer, "Candidate_Id", "Firstname", cV.Candidate_Id);
            return View(cV);
        }

        // GET: CVs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CV cV = db.CV.Find(id);
            if (cV == null)
            {
                return HttpNotFound();
            }
            return View(cV);
        }

        // POST: CVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CV cV = db.CV.Find(id);
            db.CV.Remove(cV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ProfileFreelancer(CVViewModel model)
        {
            if (ModelState.IsValid)
            {
                var candidate = db.Freelancer.Add(model.Freelancer);

                db.SaveChanges();


                model.CV.Candidate_Id = candidate.Candidate_Id;


                //CV_ID får 0 värde och det är därför vi summerar 1 till vår query 
                model.CV.CV_Id = db.CV.Max(x => x.CV_Id) + 1;

                var cv = db.CV.Add(model.CV);

                db.SaveChanges();

                var languages = new string[] { model.SelectedLanguage };

                var l = new Language
                {
                    CV_Id = cv.CV_Id,
                    Candidate_Id = candidate.Candidate_Id,
                    Swedish = languages.Contains("2") ? "True" : "False",
                    English = languages.Contains("3") ? "True" : "False",
                    French = languages.Contains("4") ? "True" : "False",
                    Spanish = languages.Contains("5") ? "True" : "False",
                    German = languages.Contains("6") ? "True" : "False",
                    Norwegian = languages.Contains("7") ? "True" : "False",
                    Danish = languages.Contains("8") ? "True" : "False",
                    Finnish = languages.Contains("9") ? "True" : "False",
                };

                db.Language.Add(l);

                var professions = new string[] { model.SelectedProfession };

                var p = new Profession
                {
                    CV_Id = cv.CV_Id,
                    Candidate_Id = candidate.Candidate_Id,

                    Webbdeveloper = professions.Contains("2") ? "True" : "False",
                    Systemdeveloper = professions.Contains("3") ? "True" : "False",
                    Programmer = professions.Contains("4") ? "True" : "False",
                    Softwareengineer = professions.Contains("5") ? "True" : "False",
                    Frontenddeveloper = professions.Contains("6") ? "True" : "False",
                    Backenddeveloper = professions.Contains("7") ? "True" : "False",
                    Javadeveloper = professions.Contains("8") ? "True" : "False",
                    Scrummaster = professions.Contains("9") ? "True" : "False",
                };

                db.Profession.Add(p);

                var skills = new string[] { model.SelectedSkill };

                var s = new Skills
                {
                    CV_Id = cv.CV_Id,
                    Candidate_Id = candidate.Candidate_Id,
                    C_ = skills.Contains("1") ? "True" : "False",
                    JavaScript = skills.Contains("2") ? "True" : "False",
                    Java = skills.Contains("3") ? "True" : "False",
                    C__ = skills.Contains("4") ? "True" : "False",
                    JQuery = skills.Contains("5") ? "True" : "False",
                    HTML = skills.Contains("6") ? "True" : "False",
                    CSS = skills.Contains("7") ? "True" : "False",
                    SQL = skills.Contains("7") ? "True" : "False"

                };

                db.Skills.Add(s);


                db.SaveChanges();

                //return RedirectToAction("Index");
            }

            return View();
        }
    }
}

GruppAKonsult/Views/CVs/Create.cshtml
@model GruppAKonsult.ViewModels.CVViewModel

@{
    /**/                           //Vägen stämmer inte?

    ViewBag.Title = "Create";
}
@using (Html.BeginForm("Profilefreelancer", "CVs", FormMethod.Post))           

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br>
        <h2>Mitt CV</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*//Bortkommenterad orignalkod*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.CV_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CV_Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CV_Id, "", new { @class = "text-danger" })
                </div>
            </div>*@


        @*//Kommenterat bort ID då det inte ska finnas med i formuläret*@
        @*<div class="form-group">
            @Html.LabelFor(model => model.Candidate_Id, "Candidate_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">*@
        @*@Html.DropDownList("Candidate_Id", null, htmlAttributes: new { @class = "form-control" })*@
        @*@Html.ValidationMessageFor(model => model.Candidate_Id, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Drivinglicense, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Drivinglicense, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Drivinglicense, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Workexperience, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Workexperience, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Workexperience, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*//Test av eget formulär*@

        <div class="col-md-7" id="FreelancerContactInfo">
            <div class="card-header">Kontaktuppgifter</div>
            <div class="row">
                <div class="card-body">
                    @Html.LabelFor(model => model.Freelancer.Firstname, "Förnamn")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Firstname, new Dictionary<string, object> { { "placeholder", "Förnamn" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Firstname, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Firstname, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Lastname, "Efternamn")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Lastname, new Dictionary<string, object> { { "placeholder", "Efternamn" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Lastname, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Lastname, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Email, "Epost")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Email, new Dictionary<string, object> { { "placeholder", "exempel@exempel.se" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Email, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Email, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Phonenumber, "Telefonnummer")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Phonenumber, new Dictionary<string, object> { { "placeholder", "Ex. 070*******" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Phonenumber, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Phonenumber, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Nationality, "Nationalitet")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Nationality, new Dictionary<string, object> { { "placeholder", "Ex. Sverige" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Nationality, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Nationality, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Birthdate, "Födelsedatum")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Birthdate, new Dictionary<string, object> { { "placeholder", "Ex. YYMMDD" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Birthdate, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Birthdate, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Cityofbirth, "Födelseort")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Cityofbirth, new Dictionary<string, object> { { "placeholder", "Ex. Stockholm" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Cityofbirth, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Cityofbirth, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Address, "Adress")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Address, new Dictionary<string, object> { { "placeholder", "Ex. Storgatan 1" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Address, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Address, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.Postalnumber, "Postnummer")<br>
                    @Html.TextBoxFor(m => m.Freelancer.Postalnumber, new Dictionary<string, object> { { "placeholder", "Ex. 331 50" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.Postalnumber, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.Postalnumber, "", new { @class = "text-danger" })

                    @Html.LabelFor(model => model.Freelancer.City, "Stad")<br>
                    @Html.TextBoxFor(m => m.Freelancer.City, new Dictionary<string, object> { { "placeholder", "Ex. Stockholm" } })<br>
                    @*@Html.EditorFor(model => model.Freelancer.City, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Freelancer.City, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br>
    </div>

    <div class="col-md-7" id="Profession">
        <div class="card-header">Yrke</div>
        <div class="row">
            @*//Fungerar inte ännu*@
            <div class="card-body">
                @*@Html.LabelFor(model => model.Profession, "Ange ditt huvudsakliga yrke")<br>*@
                @*@Html.ListBoxFor(m => m.SelectedProfessions, Model.ProfessionList)*@
                @*@Html.TextAreaFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })*@
                <br>
            </div>
        </div>
    </div>

    <div class="col-md-7" id="Skills">
        <div class="card-header">Färdigheter</div>
        <div class="row">
            @*//Fungerar inte ännu*@
            <div class="card-body">
                @Html.LabelFor(model => model.Freelancer.Skills, "Ange dina kompetenser och kunskaper")<br>
                @*@Html.ListBoxFor(m => m.SelectedSkills, Model.SkillsList)*@
                @Html.TextAreaFor(model => model.Freelancer.Skills, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Freelancer.Skills, "", new { @class = "text-danger" })
                <br>
            </div>
        </div>
    </div>

    <div class="col-md-7" id="Language">
        <div class="card-header">Språk</div>
        <div class="row">
            @*//Denna fungerar inte än*@
            <div class="card-body">
                @Html.LabelFor(model => model.Freelancer.Language, "Ange dina språkkunskaper")<br>
                @*@Html.ListBoxFor(m => m.SelectedLanguage, Model.LanguageList)*@
                @Html.TextAreaFor(model => model.Freelancer.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Freelancer.Language, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-7" id="Drivinglicense">
        <div class="card-header">Körkort</div>
        <div class="row">
            <div class="card-body">
                <div class="custom-control custom-checkbox">
                    @Html.RadioButtonFor(m => m.Drivinglicense, "Ja")
                    <label class="" for="licenseCheckYes">Ja</label>
                </div>
                <div class="custom-control custom-checkbox">
                    @Html.RadioButtonFor(m => m.Drivinglicense, new Dictionary<string, object> { { "id", "licenseCheckNo" } })
                    <label class="" for="licenseCheckNo">Nej</label>
                </div><br>
                @*@Html.LabelFor(model => model.Drivinglicense, "Svara Ja/Nej")<br>
                    @Html.EditorFor(model => model.Drivinglicense, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Drivinglicense, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-7" id="Descripton">
        <div class="card-header">Beskrivning</div>
        <div class="row">
            <div class="card-body">
                @Html.LabelFor(model => model.Description, "Skriv kort om dig själv")<br>
                @Html.TextAreaFor(m => m.Description, new Dictionary<string, object> { { "row", "5" }, { "class", "form-control" } })
                @*@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>


    <div class="col-md-7" id="Education">
        <div class="card-header">Utbildning</div>
        <div class="row">
            <div class="card-body">
                @Html.LabelFor(model => model.Education, "Ange skolans namn, datum, ämne och examen")<br>
                @Html.TextAreaFor(m => m.Education,
                      new Dictionary<string, object> { { "id","educationTextarea" }, { "row","5" }, { "class","form-control" } })

                @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

    <div class="col-md-7" id="Workexperience">
        <div class="card-header">Arbetslivserfarenhet</div>
        <div class="row">
            <div class="card-body">
                @Html.LabelFor(model => model.Education, "Ange företag, datum och arbetsuppgifter")<br>
                @Html.TextAreaFor(m => m.Workexperience,
                      new Dictionary<string, object> { { "id","workTextarea" }, { "row","5" }, { "class","form-control" } })
                @Html.ValidationMessageFor(model => model.Workexperience, "", new { @class = "text-danger" })
                <br>
                <br>
            </div>
        </div>
    </div>

    <a href='@Url.Action("ProfileFreelancer", "ProfileFreelancer")'>
        <input id="EditBtn" type='button' class="btn btn-primary btn-lg" value='Spara' />
    </a>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GruppAKonsult/Views/CVs/Delete.cshtml
@model GruppAKonsult.Models.CV

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Drivinglicense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Drivinglicense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Workexperience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workexperience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Freelancer.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Freelancer.Firstname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>