GruppAKonsult/Models/Employer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.Jobbank = new HashSet<Jobbank>();
            this.Profile = new HashSet<Profile>();
        }
    
        public int Employer_Id { get; set; }
        public string Companyname { get; set; }
        public string Email { get; set; }
        public int Phonenumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobbank> Jobbank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profile { get; set; }
    }
}

GruppAKonsult/ViewModels/EmployerFindViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GruppAKonsult.Models.DomainModels;

namespace GruppAKonsult.ViewModels
{

    public class EmployerFindViewModel : CVViewModel
    {
        public IEnumerable<EmployerFindResultModel> SearchResults { get; set; }
    }
}

GruppAKonsult/ViewModels/EmployerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GruppAKonsult.Models;

namespace GruppAKonsult.ViewModels
{
    public class EmployerViewModel
    {
        public Freelancer Freelancer { get; set; }
    }
}

GruppAKonsult/Controllers/EmployerController.cs
using GruppAKonsult.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GruppAKonsult.Models.DomainModels;
using GruppAKonsult.ViewModels;

namespace GruppAKonsult.Controllers
{
    public class EmployerController : Controller
    {

        GruppAKonsult_dbEntities2 db = new GruppAKonsult_dbEntities2();


        // GET: Employer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EmployerView()
        {
            return View();
        }

        [HttpGet]
        public ActionResult EmployerFind()
        {
            var model = new EmployerFindViewModel();

            return View(model);
        }

        public ActionResult FreelancerProfileView()
        {
            return View();
        }

        public ActionResult ShowCV(int? id)
        {
            if (!id.HasValue)
            {
                return View();
            }

            var model = new ProfileFreelancerViewModel();

            try
            {
                var candidateId = id.HasValue ? id.Value : 0;

                var freelancer = db.Freelancer
                    //.Include(x => x.Skills)
                    .FirstOrDefault(x => x.Candidate_Id == candidateId);

                if (freelancer != null)
                {
                    model.Freelancer = freelancer;
                }

                var cvId = db.CV.FirstOrDefault(x => x.Candidate_Id == candidateId)?.CV_Id;
                var skills = db.Skills.FirstOrDefault(x => x.Candidate_Id == candidateId && x.CV_Id == cvId);

                if (skills != null)
                {
                    model.CandidateSkill = string.Format("{0}{1}{2}{3}{4}{5}{6}",
                        (skills.C_ == "True" ? "C#" : ""),
                        (skills.SQL == "True" ? "SQL" : ""),
                        (skills.JavaScript == "True" ? "Javascript" : ""),
                        (skills.Java == "True" ? "Java" : ""),
                        (skills.CSS == "True" ? "CSS" : ""),
                        (skills.HTML == "True" ? "HTML" : ""),
                        (skills.JQuery == "True" ? "JQuery" : "")
                    );
                }

                var profession = db.Profession.FirstOrDefault(x => x.Candidate_Id == candidateId && x.CV_Id == cvId);


                if (profession != null)
                {
                    model.CandidateProfession = string.Format("{0}{1}{2}{3}{4}{5}{6}{7}",
                        (profession.Webbdeveloper == "True" ? "Webbdeveloper" : ""),
                        (profession.Backenddeveloper == "True" ? "Backenddeveloper" : ""),
                        (profession.Frontenddeveloper == "True" ? "Frontenddeveloper" : ""),
                        (profession.Javadeveloper == "True" ? "Javadeveloper" : ""),
                        (profession.Programmer == "True" ? "Programmer" : ""),
                        (profession.Scrummaster == "True" ? "Scrummaster" : ""),
                        (profession.Softwareengineer == "True" ? "Softwareengineer" : ""),
                        (profession.Systemdeveloper == "True" ? "Systemdeveloper" : "")
                    );
                }

                var language = db.Language.FirstOrDefault(x => x.Candidate_Id == candidateId && x.CV_Id == cvId);

                if (language != null)
                {
                    model.CandidateLanguage = string.Format("{0}{1}{2}{3}{4}{5}{6}{7}",
                        (language.Danish == "True" ? "Danska" : ""),
                        (language.Spanish == "True" ? "Spanska" : ""),
                        (language.English == "True" ? "Engelska" : ""),
                        (language.Finnish == "True" ? "Finska" : ""),
                        (language.French == "True" ? "Franska" : ""),
                        (language.German == "True" ? "Tyska" : ""),
                        (language.Swedish == "True" ? "Svenska" : ""),
                        (language.Norwegian == "True" ? "Norska" : "")
                    );

                }

            }
            catch (Exception ex)
            {

            }


            return View(model);
        }


        [HttpPost]
        public ActionResult EmployerFind(EmployerFindViewModel model)
        {

            // Fråga till databasen via SQL
            var query = (from f in db.Freelancer
                join p in db.Profession on f.Candidate_Id equals p.Candidate_Id
                join l in db.Language on f.Candidate_Id equals l.Candidate_Id
                join s in db.Skills on f.Candidate_Id equals s.Candidate_Id
                select new EmployerFindResultModel
                {
                   Candidate_Id = f.Candidate_Id,
                   Firstname =  f.Firstname,
                   Lastname  = f.Lastname,
                    Professions = ((p.Webbdeveloper == "True" ? "Webbutvecklare," : "") +
                                   (p.Systemdeveloper == "True" ? "Systemutvecklare," : "") +
                                   (p.Programmer == "True" ? "Programmerare," : "") +
                                   (p.Softwareengineer == "True" ? "Mjukvaruutveklare," : "") +
                                   (p.Frontenddeveloper == "True" ? "Frontendutvecklare," : "") +
                                   (p.Backenddeveloper == "True" ? "Backendutvecklare," : "") +
                                   (p.Javadeveloper == "True" ? "Javautvecklare," : "") +
                                   (p.Scrummaster == "True" ? "Scrummaster," : "")),
                    Languages = ((l.Swedish == "True" ? "Svenska," : "") +
                                 (l.English == "True" ? "Engelska," : "") +
                                 (l.French == "True" ? "Franska," : "") +
                                 (l.Spanish == "True" ? "Spanska," : "") +
                                 (l.German == "True" ? "Tyska," : "") +
                                 (l.Norwegian == "True" ? "Norska," : "") +
                                 (l.Danish == "True" ? "Danska," : "") +
                                 (l.Finnish == "True" ? "Finska," : "")),
                    Skills = ((s.C_ == "True" ? "C#" : "") +
                              (s.JavaScript == "True" ? "JavaScript," : "") +
                              (s.Java == "True" ? "Java," : "") +
                              (s.C__ == "True" ? "C++" : "") +
                              (s.JQuery == "True" ? "JQuery," : "") +
                              (s.HTML == "True" ? "HTML," : "") +
                              (s.CSS == "True" ? "CSS," : "") +
                              (s.SQL == "True" ? "SQL," : ""))
                }).ToList();


            //Vår sökfunktion
            var list = new List<EmployerFindResultModel>();
            var professionKey = model.ProfessionList.FirstOrDefault(x => x.Value == model.SelectedProfession)?.Text;
            
            if (professionKey != null)
            {
                 list = query.Where(x => x.Professions.Contains(professionKey)).ToList();
            }

            var skillKey = model.SkillsList.FirstOrDefault(x => x.Value == model.SelectedSkill)?.Text;

            if (skillKey != null)
            {
                list = query.Where(x => x.Skills.Contains(skillKey)).ToList();
            }

            var languageKey = model.LanguageList.FirstOrDefault(x => x.Value == model.SelectedLanguage)?.Text;

            if (languageKey != null)
            {
                list = query.Where(x => x.Languages.Contains(languageKey)).ToList();
            }

            model.SearchResults = list;

            return View(model);


        }

        

    }
}

GruppAKonsult/Controllers/EmployersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GruppAKonsult.Models;

namespace GruppAKonsult.Controllers
{
    public class EmployersController : Controller
    {
        private GruppAKonsult_dbEntities2 db = new GruppAKonsult_dbEntities2();

        // GET: Employers
        //public ActionResult Index()
        //{
        //    return View(db.Employer.ToList());
        //}
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employer employer = db.Employer.Find(id);
            if (employer == null)
            {
                return HttpNotFound();
            }
            return View(employer);
        }

        // GET: Employers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Employer_Id,Companyname,Email,Phonenumber")] Employer employer)
        {
            if (ModelState.IsValid)
            {
                db.Employer.Add(employer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employer);
        }

        // GET: Employers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employer employer = db.Employer.Find(id);
            if (employer == null)
            {
                return HttpNotFound();
            }
            return View(employer);
        }

        // POST: Employers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Employer_Id,Companyname,Email,Phonenumber")] Employer employer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employer);
        }

        // GET: Employers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employer employer = db.Employer.Find(id);
            if (employer == null)
            {
                return HttpNotFound();
            }
            return View(employer);
        }

        // POST: Employers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employer employer = db.Employer.Find(id);
            db.Employer.Remove(employer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GruppAKonsult/Views/Employer/EmployerFind.cshtml
@using GruppAKonsult.Controllers
@model GruppAKonsult.ViewModels.EmployerFindViewModel
@{
    ViewBag.Title = "EmployerFind";
}



@using (Html.BeginForm("EmployerFind", "Employer", FormMethod.Post))
{
    <div class="col-md-10">
        <br>
        <h3 class="card-header">Sök kandidat</h3><br />
        <div class="row">
            <div class="form-group col-md-2">
                <label class="control-label">Yrkesområde</label><br />
                <div>
                    @if (Model.ProfessionList != null)
                    {
                        @Html.DropDownListFor(m => m.SelectedProfession, Model.ProfessionList, new Dictionary<string, object> { { "class", "form-control" } })
                    }
                </div>
            </div>
            <br>
            <div class="form-group col-md-2">
                <label class="control-label">Kompetenser</label><br />
                <div>
                    @if (Model.SkillsList != null)
                    {
                        @Html.DropDownListFor(m => m.SelectedSkill, Model.SkillsList, new Dictionary<string, object> { { "class", "form-control" } })
                    }
                </div>
            </div>
            <br>
            @*<div class="form-group col-md-2">
                    <label class="control-label">Språk</label><br />

                    @if (Model.LanguageList != null)
                    {
                        @Html.DropDownListFor(m => m.SelectedLanguage, Model.LanguageList, new Dictionary<string, object> { { "class", "form-control" } })
                    }
                </div>*@
            @*<div class="form-group col-md-2">
                    <label class="control-label">Stad</label><br />

                    @if (Model.CityList != null)
                    {
                        @Html.DropDownListFor(m => m.SelectedCity, Model.CityList, new Dictionary<string, object> { { "class", "form-control" } })
                    }
                </div>*@
            <div class="form-group col-md-2">
                <br>
                <a>
                    <input type='submit' class="btn btn-primary btn-lg" value='SÖK' />
                </a>
            </div>
        </div>
    </div>
    <br>



    @*<div class="row">
            <div class="col-4">

                <div class="form-group">
                    <label class="control-label">City</label>
                    <div>
                        @if (Model.CityList != null)
                        {
                            @Html.DropDownListFor(m => m.SelectedCity, Model.CityList, new Dictionary<string, object> {{"class", "form-control"}})
                        }
                    </div>
                </div>
            </div>




        </div>*@




    @*<div class="col-md-1">

            <br/><br/>
            <a>
                <input type='submit' class="btn btn-primary btn-lg" value='SÖK'/>
            </a>
        </div>*@

    <div class="row">
        <div class="col-md-10">
            <h3 class="card-header">Resultat</h3>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <th>
                            <h5 class="card-title">Förnamn</h5>
                        </th>
                        <th>
                            <h5 class="card-title">Efternamn</h5>
                        </th>
                        <th>
                            <h5 class="card-title">Yrke</h5>
                        </th>
                        <th>
                            <h5 class="card-title">Kompetens</h5>
                        </th>
                        <th></th>
                    </tr>


                    @if (Model.SearchResults != null && Model.SearchResults.Any())
                    {
                        foreach (var item in Model.SearchResults)
                        {
                            <tr>
                                <td>
                                    @item.Firstname
                                </td>
                                <td>
                                    @item.Lastname
                                </td>
                                <td>
                                    @item.Professions
                                </td>
                                <td>
                                    @item.Skills
                                </td>
                                <td>@Html.ActionLink("Visa CV", "ShowCV", "Employer", new { id = item.Candidate_Id }, new { @class = "btn btn-sm btn-primary" })</td>
                                <th></th>
                            </tr>
                        }
                    }

                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">

        $(function() {

            var professionId = "#@Html.IdFor(m => m.SelectedProfession)";
            var skillId = "#@Html.IdFor(m => m.SelectedSkill)";


            $(professionId).change(function () {

                let val = $(this).val(); //profession

                $(skillId).children("option").hide();

                if (val == "2") {


                    $(skillId).children("option[value='6']").show(); //refers to skills
                    $(skillId).children("option[value='7']").show(); 
                    $(skillId).children("option[value='8']").show();
                    $(skillId).children("option[value='3']").show(); 
                }
                else if (val == "3") {

                    $(skillId).children("option[value='2']").show(); //refers to skills
                    $(skillId).children("option[value='5']").show(); 
                }
                else if (val == "4") {

                    $(skillId).children("option[value='2']").show(); //refers to skills
                    $(skillId).children("option[value='3']").show();
                    $(skillId).children("option[value='5']").show();
                    $(skillId).children("option[value='6']").show();
                    $(skillId).children("option[value='7']").show();
                    $(skillId).children("option[value='8']").show();
                    $(skillId).children("option[value='9']").show();

                }
                else if (val == "5") {

                    $(skillId).children("option[value='2']").show(); //refers to skills
                    $(skillId).children("option[value='3']").show();
                    $(skillId).children("option[value='5']").show();
                    $(skillId).children("option[value='6']").show();
                    $(skillId).children("option[value='7']").show();
                    $(skillId).children("option[value='8']").show();
                    $(skillId).children("option[value='9']").show();
                }

                else if (val == "6") {

                    $(skillId).children("option[value='6']").show(); //refers to skills
                    $(skillId).children("option[value='7']").show(); 
                    $(skillId).children("option[value='8']").show();
                    $(skillId).children("option[value='3']").show(); 
                }
                else if (val == "7") {

                    $(skillId).children("option[value='2']").show(); //refers to skills
                    $(skillId).children("option[value='5']").show();
                }

                else if (val == "8") {

                    $(skillId).children("option[value='3']").show(); //refers to skills
                    $(skillId).children("option[value='6']").show();
                }
                else if (val == "9") {

                  
                    $(skillId).children("option[value='9']").show();
                }

               

            })

        })

    </script>

}

GruppAKonsult/Views/Employer/EmployerView.cshtml
@{
    ViewBag.Title = "Företagsida";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br>
<h1>It Company</h1><br>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            <h3 class="card-header">Kontaktuppgifter</h3>
            <div class="card-body">

                <h5 class="card-title">Adress</h5>
                <h6 class="card-subtitle text-muted"> Itvägen 1</h6><br>
                <h6 class="card-subtitle text-muted"> 112233, Malmö </h6><br>
                <h6 class="card-subtitle text-muted"> Sverige </h6><br>

                <h5 class="card-title">Epost</h5>
                <h6 class="card-subtitle text-muted">ItCompany@gmail.com</h6><br>

                <h5 class="card-title">Telefonnummer</h5>
                <h6 class="card-subtitle text-muted">040112233</h6><br>

                <h5 class="card-title">Stad</h5>
                <h6 class="card-subtitle text-muted">Malmö</h6><br>
            </div>
        </div>
    </div>
    <hr />
    <br>
    <a href='@Url.Action("EmployerFind", "Employer")'>
    <input type='button' class="btn btn-primary btn-lg" value='Sök kandidat' />
    </a>
 </div>

   



        @*<div class="col-md-10">
                <br /><h5 class="card-title">Förnamn</h5>
            </div>
            <div class="col-md-2">
                <br /><h5 class="card-title">Efternamn</h5>
            </div>
            <div class="col-md-2">
                <h5 class="card-title">Yrke</h5>
            </div>
            <div class="col-md-2">
                <br /><h5 class="card-title">Kompetens</h5>
            </div>
            <div class="col-md-2">
                <br /><h5 class="card-title">Språk</h5>
            </div>
            <div class="col-md-2">
                <br /><h5 class="card-title">Stad</h5>
            </div>*@

GruppAKonsult/Views/Employer/FreelancerProfileView.cshtml
@{
    ViewBag.Title = "FreelancerProfileView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br>
<h1>Petter Petterssons profil</h1><br><br>

<div class="jumbotron">
    <h2>Mitt CV</h2><br>
    <div class="row">
        <div class="col-md-6">
            <div class="card-header">Kontakuppgifter</div>
            <div class="card-body">
                <h5 class="card-title">Namn</h5>
                <h6 class="card-subtitle text-muted"> Petter Pettersson</h6><br>

                <h5 class="card-title">Epost</h5>
                <h6 class="card-subtitle text-muted">PetterPetterson@gmail.com</h6><br>

                <h5 class="card-title">Telefonnummer</h5>
                <h6 class="card-subtitle text-muted">0700000000</h6><br>

                <h5 class="card-title">Födelsedatum</h5>
                <h6 class="card-subtitle text-muted">19801030</h6><br>

                <h5 class="card-title">Adress</h5>
                <h6 class="card-subtitle text-muted">Storgatan 1</h6><br>

                <h5 class="card-title">Stad</h5>
                <h6 class="card-subtitle text-muted">Stockholm</h6><br>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card-header">Foto</div>
            <div class="card-body">
                <img style="height: auto; width: auto;"  src="~/Content/Pictures/Nerd.png" alt="Card image"><br><br>
                <div class="row">
                    <link id="LinkGithub"><a href="https://github.com/"> <img style="text-align:center; margin: 15px; height:70px; width:70px; display:inline-block;" src="~/Content/Pictures/github.png"> </a>
                    <link id="LinkLinkedin"><a href="https://www.linkedin.com/"> <img style="text-align:center; margin: 15px; height:70px; width:70px; display:inline-block;" src="~/Content/Pictures/linkedin.png"></a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <br />

        <a href='@Url.Action("ShowCV", "Employer")'>
            <input id="ShowBtn" type='button' class="btn btn-primary btn-lg" value='Visa CV' />
        </a><br><br>
    </div>

GruppAKonsult/Views/Employer/ShowCV.cshtml
@model GruppAKonsult.ViewModels.ProfileFreelancerViewModel

@{
    ViewBag.Title = "ShowCV";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br>
<h2>CV</h2>
<br />

<div class="row">
    @*<div class="form-group col-md-2">
            @Html.ActionLink("Visa profil", "UpdatedCV", "ProfileFreelancer", new { id = @Model.Freelancer.Candidate_Id}, new { @class = "btn btn-sm btn-primary"})
        </div>

        <br>*@

    <div class="form-group col-md-2">
        <a href='@Url.Action("EmployerFind", "Employer")'>
            <input id="SearchBtn" type='button' class="btn btn-primary btn-lg" value='Tillbaka till sök' />
        </a>
    </div>

    <div class="form-group col-md-2">
        <a href='@Url.Action("EmployerView", "Employer")'>
            <input id="CustomerBtn" type='button' class="btn btn-primary btn-lg" value='Min profilsida' />
        </a>
    </div>


    <div class="form-group col-md-2">
        <a href='@Url.Action("FreelancerProfileView", "Employer")'>
            <input id="SearchBtn" type='button' class="btn btn-primary btn-lg" value='Kandidatens profil' />
            </a>
    </div>
</div>
<br>
<br />
<div class="card border-primary" style="max-width: 80rem;">
    <div class="card-header">Kontaktuppgifter</div>
    <div class="card-body">
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Förnamn</label><br />
            <h6>@Model.Freelancer.Firstname</h6>
        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Efternamn</label><br />
            <h6>@Model.Freelancer.Lastname</h6>
        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Nationalitet</label><br />
            <h6>@Model.Freelancer.Nationality</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Epost</label><br />
            <h6>@Model.Freelancer.Email</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Telefonnummer</label><br />
            <h6>@Model.Freelancer.Phonenumber</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Födelsedatum</label><br />
            <h6>@Model.Freelancer.Birthdate</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Födelseort</label><br />
            <h6>@Model.Freelancer.Cityofbirth</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Adress</label><br />
            <h6>@Model.Freelancer.Address</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Postnummer</label><br />
            <h6>@Model.Freelancer.Postalnumber</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Stad</label><br />
            <h6>@Model.Freelancer.City</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Yrke</label><br />
            <h6>@Model.CandidateProfession</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Kompetens</label><br />
            <h6>@Model.CandidateSkill</h6>

        </div>
        <div class="form-group">
            <label class="col-form-label" for="inputDefault">Språk</label><br />
            <h6>@Model.CandidateLanguage</h6>

        </div>
    </div>
</div><br>